Repository shrey141102/PythonProjects, pull requests merged in 2023-12, with the labels that each got.

#11 Web Scraper application code added
  WebScraper/test_web_scraper.py
  WebScraper/web_scraper.py
Labels: kwoc23, kwoc

#18 Created Chatapp using flask and socketio. Fixes #issue-number-3
  chatapp/main.py
  chatapp/static/style.css
  chatapp/templates/base.html
  chatapp/templates/home.html
  chatapp/templates/room.html
Labels: kwoc

#23 Folder change
  QR_Generator/main.py
  QR_Generator/requirement.txt
  QR_Generator/static/style.css
  QR_Generator/templates/index.html
Labels: kwoc

#30 Rock-Paper-Scissors Fixed : Bugs description in README file
  rock-paper-scissors/README.md
  rock-paper-scissors/main.py
Labels: bug

#31 Tic - Tac -Toe
  Tic tae toe/game.py
Labels: kwoc23, kwoc, new-project

#25 pifiglet multiple fonts
  PiFiglet/Formatted Text.py
  PiFiglet/fonts.txt
Labels: kwoc

#56 Added two projects - Memory Tiles and Num Sherlock under #KWoC 2023
  Memory Tiles/game.py
  NumSherlock/game.py
  NumSherlock/images/index.txt
  NumSherlock/images/last1 (1).png
  NumSherlock/images/lastsec1 (1).png
  NumSherlock/images/private-detective.png
  NumSherlock/images/startimg.png (2).png
  README.md
Labels: kwoc23
